# Generated by Django 5.0.4 on 2024-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='moment',
        ),
        migrations.AddField(
            model_name='moment',
            name='moment',
            field=models.ManyToManyField(null=True, to='app.tag'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
