# Generated by Django 5.0.4 on 2024-04-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tag_moment_moment_moment_alter_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moment',
            old_name='moment',
            new_name='tag',
        ),
    ]
